"""finalised student planner tables

Revision ID: b35cf5304e3a
Revises: 
Create Date: 2026-02-23 16:18:56.236162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35cf5304e3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_user_id'), ['user_id'], unique=False)

    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=256), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_exam_date'), ['exam_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_user_id'), ['user_id'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_scheduled_time'), ['scheduled_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_scheduled_time'))
        batch_op.drop_index(batch_op.f('ix_task_module'))
        batch_op.drop_index(batch_op.f('ix_task_completed'))

    op.drop_table('task')
    with op.batch_alter_table('exam', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_module'))
        batch_op.drop_index(batch_op.f('ix_exam_exam_date'))

    op.drop_table('exam')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_user_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_title'))
        batch_op.drop_index(batch_op.f('ix_assignment_due_date'))
        batch_op.drop_index(batch_op.f('ix_assignment_completed'))

    op.drop_table('assignment')
    op.drop_table('user')
    # ### end Alembic commands ###
