"""modified assignment and user table

Revision ID: d0df6fc88dcb
Revises: 26f8bd7ac0d5
Create Date: 2026-02-22 23:56:15.994744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0df6fc88dcb'
down_revision = '26f8bd7ac0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('date_completed', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_title'), ['title'], unique=False)

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_completed'))
        batch_op.drop_index(batch_op.f('ix_task_title'))

    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=False),
    sa.Column('date_completed', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_completed'), ['completed'], unique=False)

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_title'))
        batch_op.drop_index(batch_op.f('ix_assignment_completed'))

    op.drop_table('assignment')
    # ### end Alembic commands ###
